#!/usr/bin/python3
import socket

s = socket.socket(socket.AF_INET, socket.SOCK_DGRAM, 0)

ip_addr = '172.0.0.1'
port = 12345

#connect to a remote socket at address
s.connect((ip_addr, port))          #typically used for TCP

message = b"Hello"

#send data to the socket, the socket should not be connected to a remote socket. 
#Typically used for TCP
s.sendto(message, (ip_addr, port))

#Receive data from the socket. the return value is a pair (bytes, address) where bytes is a bytes object
#representing the data received and address it the address of the socket sending the data
data, addr = s.recvfrom(1024)

#Default encoding is 'utf-8'
print(data.decode())
